name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb://admin:password@localhost:27017/admin'
  

    
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        # services:
        #   mongo:
        #     image: mongo:latest
        #     ports:
        #       - 27017:27017
            # options: --health-cmd="exit 1" --health-interval=10s --health-timeout=5s --health-retries=3
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: 20
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
